// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who can reach a server at this address.
 */
export type AddressKind = "loopback" | "lan" | "vpn" | "public" | "link_local";
