// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of an archive, for the restore preview.
 */
export type ArchiveEntry = { path: string, size: number, };
