// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What gets downloaded: either the server jar itself, or an installer that has
 * to be run to produce a server.
 */
export type ArtifactKind = "server_jar" | "installer";
