// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKind } from "./ArtifactKind";

export type Artifact = { url: string, fileName: string, kind: ArtifactKind, sha1: string | null, sha256: string | null, md5: string | null, size: number | null, 
/**
 * The build/loader version this artifact corresponds to, when the provider
 * has one (Paper build number, Fabric loader version, Forge version).
 */
build: string | null, 
/**
 * Java major version the server requires, when the provider states it.
 */
javaMajor: number | null, };
