// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";
import type { Scope } from "./Scope";

export type Backup = { id: number, instanceId: number, path: string, format: Format, scope: Scope, 
/**
 * manual | scheduled | pre_restore
 */
kind: string, label: string | null, sizeBytes: number, createdAt: string, };
