// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";
import type { Scope } from "./Scope";

/**
 * Options for one backup run.
 */
export type BackupOptions = { format: Format, scope: Scope, level: number | null, label: string | null, 
/**
 * Extra paths or `*.ext` patterns to leave out.
 */
exclude: Array<string>, };
