// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BannedPlayer = { uuid: string, name: string, created: string, source: string, expires: string, reason: string, };
