// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable build for a given Minecraft version (Paper build, Forge
 * version, Fabric loader, …). Empty for Vanilla.
 */
export type BuildEntry = { id: string, stable: boolean, label: string | null, };
