// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build information, also shown in the About dialog.
 */
export type BuildInfo = { version: string, 
/**
 * Commit the binary was built from, `unknown` outside a git checkout.
 */
gitSha: string, platform: string, arch: string, dbPath: string, logDir: string, instanceRoot: string, 
/**
 * Highest applied migration, which is what a schema question really asks.
 */
schemaVersion: number | null, };
