// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One filterable category, as the source publishes it.
 */
export type Category = { 
/**
 * The value to send back in a search.
 */
id: string, 
/**
 * What to show in the dropdown.
 */
name: string, };
