// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloneInstanceInput = { sourceId: number, name: string, path: string, 
/**
 * Copying worlds is the common case; skipping them gives a fresh map with
 * the same mods and configuration.
 */
includeWorlds: boolean, };
