// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedLine } from "./ParsedLine";

/**
 * Console output, batched: one event carries up to a few hundred lines so a
 * server generating chunks cannot flood the IPC bridge.
 */
export type ConsoleEvent = { uuid: string, lines: Array<ParsedLine>, };
