// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";

/**
 * One entry of the content-type dropdown.
 */
export type ContentTypeOption = { contentType: ContentType, 
/**
 * False for what this server cannot load — shown, and marked.
 */
installable: boolean, clientOnly: boolean, };
