// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the browser is showing: mods, plugins, packs, and the client-side kinds
 * a server has no use for.
 *
 * Each source calls these something different — a Modrinth "project type", a
 * CurseForge "class id" — and neither name appears above this boundary.
 */
export type ContentType = "mod" | "plugin" | "modpack" | "data_pack" | "resource_pack" | "shader";
