// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyKind } from "./DependencyKind";

export type Dependency = { kind: DependencyKind, 
/**
 * One of these is always set.
 */
projectId: string | null, versionId: string | null, };
