// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A JDK this app could download, as the confirmation shows it.
 */
export type DownloadOffer = { featureVersion: number, releaseName: string, openjdkVersion: string, sizeBytes: number, os: string, arch: string, fileName: string, };
