// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Files an archive would contain, and how big they are uncompressed.
 */
export type Estimate = { files: number, 
/**
 * Uncompressed bytes. Compression only ever makes the archive smaller, so
 * this is a safe upper bound for the free-space check.
 */
bytes: number, };
