// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EulaStatus = { accepted: boolean, 
/**
 * Whether `eula.txt` exists at all yet.
 */
fileExists: boolean, path: string, acceptedAt: string | null, url: string, };
