// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The routers this machine sends traffic through, as manual port-forwarding
 * instructions need one to name.
 */
export type Gateway = { address: string, interface: string, };
