// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheck } from "./HealthCheck";
import type { HealthStatus } from "./HealthStatus";

/**
 * Everything the self-check looked at.
 */
export type Health = { checks: Array<HealthCheck>, 
/**
 * The worst status among the checks, so the UI has one thing to show.
 */
status: HealthStatus, checkedAt: string, };
