// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";

/**
 * One thing that was checked, and what it found.
 */
export type HealthCheck = { 
/**
 * Short label, e.g. "Database integrity".
 */
name: string, status: HealthStatus, 
/**
 * One line saying what was found, whether it passed or not.
 */
detail: string, };
