// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectConfidence } from "./DetectConfidence";
import type { LaunchKind } from "./LaunchKind";
import type { ServerType } from "./ServerType";

export type ImportCandidate = { path: string, suggestedName: string, serverType: ServerType, mcVersion: string | null, loaderVersion: string | null, launchKind: LaunchKind, launchTarget: string | null, eulaAccepted: boolean, worlds: Array<string>, confidence: DetectConfidence, 
/**
 * Whether a previous install of this app already managed the folder.
 */
fromManifest: boolean, 
/**
 * Human-readable reasons, shown in the confirmation dialog.
 */
notes: Array<string>, };
