// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceStatus } from "./InstanceStatus";
import type { LaunchKind } from "./LaunchKind";
import type { ServerType } from "./ServerType";

export type InstanceView = { id: number, uuid: string, name: string, path: string, folderExists: boolean, status: InstanceStatus, serverType: ServerType, mcVersion: string, loaderVersion: string | null, launchKind: LaunchKind, launchTarget: string | null, javaPath: string | null, javaMajor: number | null, jvmArgs: Array<string>, serverArgs: Array<string>, minRamMb: number, maxRamMb: number, eulaAccepted: boolean, eulaAcceptedAt: string | null, autoStart: boolean, autoRestart: boolean, restartMax: number, restartWindowS: number, stopTimeoutS: number, 
/**
 * `mods` or `plugins`, derived from the server type.
 */
contentDir: string, color: string | null, notes: string | null, lastExitCode: number | null, lastStartedAt: string | null, lastStoppedAt: string | null, pid: number | null, createdAt: string, updatedAt: string, };
