// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";

/**
 * Everything a pack install needs from the user.
 */
export type InstallPackInput = { source: SourceId, projectId: string, versionId: string, 
/**
 * Name for the new instance.
 */
name: string, 
/**
 * Absolute folder for it.
 */
path: string, maxRamMb: number | null, };
