// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledMod = { id: number, fileName: string, displayName: string | null, version: string | null, loader: string | null, mcVersion: string | null, source: string, projectId: string | null, versionId: string | null, pageUrl: string | null, sizeBytes: number | null, enabled: boolean, pinned: boolean, 
/**
 * Newest version id seen by an update check, when it differs.
 */
updateVersionId: string | null, installedAt: string, };
