// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionalDependency } from "./OptionalDependency";
import type { PlannedMod } from "./PlannedMod";

export type InstallPlan = { 
/**
 * Everything that would be installed, roots first.
 */
install: Array<PlannedMod>, optional: Array<OptionalDependency>, 
/**
 * Projects the plan says are incompatible with something being installed.
 */
incompatible: Array<string>, totalSize: number, };
