// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceStatus } from "./InstanceStatus";

export type InstanceStatusEvent = { uuid: string, status: InstanceStatus, exitCode: number | null, };
