// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchKind } from "./LaunchKind";
import type { ServerType } from "./ServerType";

/**
 * `.msm/instance.json`. The database row is authoritative during normal
 * operation; this file exists so a lost database or a copied folder is
 * recoverable, and it is only read on import.
 */
export type InstanceManifest = { schema: number, uuid: string, name: string, serverType: ServerType, mcVersion: string, loaderVersion: string | null, launchKind: LaunchKind, launchTarget: string | null, jvmArgs: Array<string>, serverArgs: Array<string>, minRamMb: number, maxRamMb: number, javaPath: string | null, eulaAccepted: boolean, createdAt: string, updatedAt: string, };
