// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime status. Only ever derived — never read back from the database as truth.
 */
export type InstanceStatus = "stopped" | "starting" | "running" | "stopping" | "crashed" | "unmanaged" | "missing";
