// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JarMetadata = { 
/**
 * Which file the metadata came from, for the UI to explain itself.
 */
format: string, id: string | null, name: string | null, version: string | null, description: string | null, authors: Array<string>, 
/**
 * Loader identifiers the jar declares.
 */
loaders: Array<string>, 
/**
 * Minecraft versions or ranges the jar declares, as written.
 */
gameVersions: Array<string>, };
