// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaSource = "path" | "java_home" | "classpath" | "registry" | "common_dir" | "manual";
