// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How strictly a server type wants the Java version its Minecraft release
 * was built against.
 *
 * Vanilla and the Bukkit-family servers are happy on anything newer: they are
 * plain Java programs, and a 1.16 server on Java 17 behaves. The mod loaders
 * are not, because Mixin rewrites bytecode at load time and a class file
 * format it does not know about produces failures deep inside somebody else's
 * mod — the kind nobody can diagnose from the stack trace.
 */
export type JavaFit = "floor" | "exact";
