// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaSource } from "./JavaSource";

export type JavaRuntime = { id: number, 
/**
 * Absolute path to the `java` binary.
 */
path: string, major: number, fullVersion: string | null, vendor: string | null, arch: string | null, source: JavaSource, valid: boolean, detectedAt: string, };
