// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadOffer } from "./DownloadOffer";
import type { JavaFit } from "./JavaFit";

/**
 * What the machine can offer for a required version, and what it would cost.
 */
export type JavaPlan = { requiredMajor: number, 
/**
 * Whether this server type takes anything newer or wants that exact major.
 */
fit: JavaFit, 
/**
 * The reasoning, as one sentence for the create dialog: which Java the
 * release is tested on, what this computer has, and what follows.
 */
reason: string, 
/**
 * Set when a runtime would be used that the rule does not prefer — a pin
 * against a loader's exact major, or a server grandfathered by a start
 * that already worked. Allowed, and worth saying.
 */
warning: string | null, 
/**
 * The Java this server has already reached its Done line on, when it has.
 * The reason a stricter rule does not get to stop it.
 */
ranBeforeOn: number | null, 
/**
 * What would be pinned by the "keep using this Java" button, so the UI
 * does not have to work it out.
 */
pinnablePath: string | null, 
/**
 * The best major this computer could offer under a floor rule, when the
 * exact one is missing. Names what the user already has.
 */
installedMajor: number | null, 
/**
 * True when a pin, a managed runtime or a system JDK already satisfies it.
 */
satisfied: boolean, 
/**
 * Where the runtime that would be used came from.
 */
origin: string | null, javaPath: string | null, 
/**
 * The download to offer when nothing suitable is installed. `None` when
 * downloads are switched off or the API could not be reached.
 */
offer: DownloadOffer | null, 
/**
 * Why there is no offer, when there is none.
 */
offerError: string | null, downloadsAllowed: boolean, };
