// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaRuntime } from "./JavaRuntime";

/**
 * What the instance's Java situation looks like right now: what it needs, what
 * it would use, and whether that combination works.
 */
export type JavaStatus = { requiredMajor: number, 
/**
 * The runtime that would be used: the pinned one, or the best match.
 */
selected: JavaRuntime | null, 
/**
 * Set when the instance pins a path that is missing or unusable.
 */
pinnedPath: string | null, pinnedValid: boolean, 
/**
 * True when nothing installed satisfies the requirement.
 */
mismatch: boolean, message: string | null, };
