// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadOffer } from "./DownloadOffer";

/**
 * What the machine can offer for a required version, and what it would cost.
 */
export type JavaPlan = { requiredMajor: number, 
/**
 * True when a pin, a managed runtime or a system JDK already satisfies it.
 */
satisfied: boolean, 
/**
 * Where the runtime that would be used came from.
 */
origin: string | null, javaPath: string | null, 
/**
 * The download to offer when nothing suitable is installed. `None` when
 * downloads are switched off or the API could not be reached.
 */
offer: DownloadOffer | null, 
/**
 * Why there is no offer, when there is none.
 */
offerError: string | null, downloadsAllowed: boolean, };
