// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueKind } from "./ValueKind";

export type KeyInfo = { key: string, kind: ValueKind, description: string, default: string | null, 
/**
 * A key this build does not know: shown with a raw text editor.
 */
known: boolean, 
/**
 * Changing it needs a restart, which is true of every server property.
 */
group: string, };
