// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the server is launched. Forge/NeoForge >= 1.17 have no runnable single
 * jar; they ship `libraries/` plus an `@…_args.txt` argument file.
 */
export type LaunchKind = "jar" | "args_file" | "script";
