// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The loader a server runs, as far as mod compatibility is concerned.
 */
export type Loader = "fabric" | "forge" | "neo_forge" | "paper";
