// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A runtime this app downloaded, as the UI lists it.
 */
export type ManagedRuntime = { featureVersion: number, 
/**
 * `jdk-25.0.4+7`.
 */
releaseName: string, vendor: string, 
/**
 * Absolute path to the `java` binary inside the install.
 */
javaPath: string, installedAt: string, sizeBytes: number, 
/**
 * Names of instances that would break if this were removed.
 */
usedBy: Array<string>, };
