// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalPort } from "./LocalPort";
import type { NetAddress } from "./NetAddress";

/**
 * The same addresses, for the map's port.
 */
export type MapAddresses = { 
/**
 * BlueMap or Dynmap, as the tab names it.
 */
label: string, port: number, addresses: Array<NetAddress>, 
/**
 * What this machine can see about the map's own port.
 */
local: LocalPort, };
