// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalPort } from "./LocalPort";
import type { NetAddress } from "./NetAddress";

/**
 * The same addresses, for the map's port.
 */
export type MapAddresses = { label: string, port: number, addresses: Array<NetAddress>, 
/**
 * What this machine can see about the map's own port.
 */
local: LocalPort, 
/**
 * The address the map's web server binds to.
 */
bind: string | null, 
/**
 * True when that bind lets other machines in, which squaremap's default
 * does. A map is then as public as the port forwarding allows.
 */
reachesTheNetwork: boolean, };
