// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two map mods this app knows how to install and read.
 */
export type MapKind = "blue_map" | "dynmap" | "squaremap";
