// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapKind } from "./MapKind";

/**
 * One map a server type can run, as the create dialog's dropdown lists it.
 */
export type MapOption = { kind: MapKind, label: string, 
/**
 * The one line that makes the difference between them visible.
 */
summary: string, defaultPort: number, };
