// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the router said.
 */
export type MappingResult = { ok: boolean, 
/**
 * One sentence naming what happened, router included where it named itself.
 */
detail: string, 
/**
 * The public address the router reports, when it reports one.
 */
externalIp: string | null, 
/**
 * How long the mapping lasts, in hours, when one was made.
 */
leaseHours: number | null, };
