// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapKind } from "./MapKind";

/**
 * A map's port, and who else wants it.
 */
export type MapStatus = { 
/**
 * The map mod installed in this instance, if any.
 */
kind: MapKind | null, 
/**
 * The maps this server type could have, for the offer when it has none.
 */
available: Array<MapKind>, 
/**
 * The port its config names. `None` until the mod has written one, which
 * happens on the server's first start after installing.
 */
port: number | null, 
/**
 * Where the config lives, so the UI can point at it rather than describe it.
 */
configPath: string | null, 
/**
 * The address to open, once there is a port.
 */
url: string | null, 
/**
 * True when this server is running, which is the only time a map answers.
 */
running: boolean, 
/**
 * Another server already using this port, named. Two maps on one port is
 * the second one silently failing to start its web server.
 */
conflict: string | null, 
/**
 * True when BlueMap's config says it may not download its resources, which
 * is the state it stops in with "BlueMap is missing important resources!".
 */
downloadBlocked: boolean, 
/**
 * True when almost nothing has been rendered yet. A new map is a black
 * rectangle, which reads as broken rather than as empty.
 */
barelyRendered: boolean, 
/**
 * The world the server loads, for the render command and the hint.
 */
world: string | null, 
/**
 * The console command that renders what has already been played, when the
 * map has one. Built here so the page never assembles a command.
 */
renderCommand: string | null, };
