// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapKind } from "./MapKind";

/**
 * A map's port, and who else wants it.
 */
export type MapStatus = { 
/**
 * The map mod installed in this instance, if any.
 */
kind: MapKind | null, 
/**
 * The maps this server type could have, for the offer when it has none.
 */
available: Array<MapKind>, 
/**
 * The port its config names. `None` until the mod has written one, which
 * happens on the server's first start after installing.
 */
port: number | null, 
/**
 * Where the config lives, so the UI can point at it rather than describe it.
 */
configPath: string | null, 
/**
 * The address to open, once there is a port.
 */
url: string | null, 
/**
 * True when this server is running, which is the only time a map answers.
 */
running: boolean, 
/**
 * Another server already using this port, named. Two maps on one port is
 * the second one silently failing to start its web server.
 */
conflict: string | null, };
