// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the Map tab shows.
 */
export type MapStatus = { 
/**
 * True when squaremap is installed here.
 */
installed: boolean, 
/**
 * True when this server type could have it, for the offer when it has none.
 */
supported: boolean, 
/**
 * The port its config names. `None` until squaremap has written one, which
 * happens on the server's first start after installing.
 */
port: number | null, 
/**
 * Where the config lives, so the UI can point at it rather than describe it.
 */
configPath: string | null, 
/**
 * The address to open, once there is a port.
 */
url: string | null, 
/**
 * True when this server is running, which is the only time a map answers.
 */
running: boolean, 
/**
 * Another server already using this port, named. Two maps on one port is
 * the second one silently failing to start its web server.
 */
conflict: string | null, 
/**
 * True when almost nothing has been rendered yet. A new map is a blank
 * rectangle, which reads as broken rather than as empty.
 */
barelyRendered: boolean, 
/**
 * The world the server loads, for the hint.
 */
world: string | null, 
/**
 * The address squaremap's web server binds to, as its own config says.
 */
bind: string | null, 
/**
 * True when that bind address lets the rest of the network in. squaremap
 * ships `0.0.0.0`, so the map is on the LAN from the first start — worth
 * saying rather than presenting a loopback address as the whole truth.
 */
reachesTheNetwork: boolean, 
/**
 * The console command that renders what has already been played. Built
 * here so the page never assembles a command.
 */
renderCommand: string | null, };
