// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One resource sample, pushed as it is taken so a chart can follow live
 * without asking for the last row on a timer.
 */
export type MetricsEvent = { uuid: string, ts: string, cpuPct: number, rssBytes: number, players: number | null, };
