// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a jar might not suit the instance. Warnings, never refusals.
 */
export type Mismatch = { loader: string | null, gameVersion: string | null, };
