// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Loader } from "./Loader";
import type { ModView } from "./ModView";

/**
 * Everything the mods tab needs in one call.
 */
export type ModsView = { 
/**
 * `mods` or `plugins`, decided by the server type.
 */
contentDir: string | null, loader: Loader | null, mcVersion: string, mods: Array<ModView>, 
/**
 * Set when this instance cannot load mods at all.
 */
unsupported: string | null, };
