// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledMod } from "./InstalledMod";
import type { JarMetadata } from "./JarMetadata";
import type { Mismatch } from "./Mismatch";

/**
 * A jar in the content folder, with whatever the database and the jar itself
 * know about it.
 */
export type ModView = { fileName: string, enabled: boolean, sizeBytes: number, 
/**
 * The row from `mods`, when this app installed it.
 */
tracked: InstalledMod | null, 
/**
 * What the jar declares about itself.
 */
metadata: JarMetadata | null, 
/**
 * Set when the jar's declarations do not match the instance.
 */
mismatch: Mismatch | null, 
/**
 * Projects that depend on this one, for the uninstall warning.
 */
requiredBy: Array<string>, };
