// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a mutation was carried out, which the UI reports back to the user.
 */
export type MutationRoute = "command" | "file";
