// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One change to one list.
 */
export type Mutation = { "action": "op", player: string, 
/**
 * 1–4; the server only stores it, `/op` always grants the configured level.
 */
level: number | null, } | { "action": "deop", player: string, } | { "action": "whitelist_add", player: string, } | { "action": "whitelist_remove", player: string, } | { "action": "ban", player: string, reason: string | null, } | { "action": "pardon", player: string, } | { "action": "ban_ip", ip: string, reason: string | null, } | { "action": "pardon_ip", ip: string, };
