// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationRoute } from "./MutationRoute";
import type { PlayerLists } from "./PlayerLists";

export type MutationReport = { route: MutationRoute, command: string | null, lists: PlayerLists, };
