// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressKind } from "./AddressKind";

/**
 * One address somebody could type into Minecraft's "Add server" box.
 */
export type NetAddress = { 
/**
 * The bare address, without a port.
 */
address: string, 
/**
 * `address` or `address:port` — what is actually copied.
 */
joinable: string, kind: AddressKind, 
/**
 * The VPN product this block belongs to, when the block names one.
 */
network: string | null, 
/**
 * Who can use this address, in one sentence.
 */
audience: string, 
/**
 * The adapter it came from, as the OS names it.
 */
interface: string, };
