// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gateway } from "./Gateway";
import type { LocalPort } from "./LocalPort";
import type { MapAddresses } from "./MapAddresses";
import type { NetAddress } from "./NetAddress";

/**
 * Everything the tab shows before anything is checked.
 */
export type NetworkView = { port: number, addresses: Array<NetAddress>, gateway: Gateway | null, 
/**
 * True when the server's own `server.properties` has the whitelist on.
 */
whitelistEnabled: boolean, 
/**
 * True when the server is online-mode, which is worth saying next to a
 * VPN address: cracked clients cannot join either way.
 */
onlineMode: boolean, 
/**
 * What this machine can see about its own port right now.
 */
local: LocalPort, 
/**
 * Manual port-forwarding steps, written for this machine's router.
 */
manualSteps: Array<string>, 
/**
 * The web map's port and addresses, when one is installed. A map is a
 * second thing to share, on a second port, and somebody who forwards
 * 25565 and stops has forwarded half of it.
 */
map: MapAddresses | null, };
