// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A dependency the user may want but that is never installed automatically.
 */
export type OptionalDependency = { projectId: string, projectTitle: string, suggestedBy: string, };
