// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a launch's Java came from, for the log line and the UI.
 */
export type Origin = "pinned" | "managed" | "system";
