// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Side } from "./Side";

export type PackFile = { 
/**
 * Destination path inside the instance, as the pack states it.
 */
path: string, downloads: Array<string>, sha512: string | null, size: number | null, client: Side, server: Side, };
