// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackIndex } from "./PackIndex";

/**
 * What an import would do, shown before it runs.
 */
export type PackPlan = { index: PackIndex, installCount: number, 
/**
 * Files skipped because the pack marks them client-only.
 */
skippedClientOnly: Array<string>, totalSize: number, 
/**
 * Set when the pack targets a different Minecraft version or loader.
 */
mismatch: string | null, };
