// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerSupport } from "./ServerSupport";
import type { ServerType } from "./ServerType";

/**
 * What reading the index said about a pack.
 */
export type PackDetail = { name: string, mcVersion: string, loader: string | null, loaderVersion: string | null, 
/**
 * The server type this pack becomes, when it can become one.
 */
serverType: ServerType | null, support: ServerSupport, 
/**
 * Why it cannot run as a server, when it cannot.
 */
reason: string | null, serverFiles: number, clientOnlyFiles: number, totalBytes: number, 
/**
 * RAM the pack itself asks for, when its description says.
 */
publishedRamMb: number | null, 
/**
 * What this app would suggest otherwise, from the size of the pack.
 */
suggestedRamMb: number, };
