// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackFile } from "./PackFile";

export type PackIndex = { name: string, versionId: string | null, summary: string | null, 
/**
 * Minecraft version the pack targets.
 */
mcVersion: string, 
/**
 * Loader plus its version, as the pack declares them.
 */
loader: string | null, loaderVersion: string | null, files: Array<PackFile>, };
