// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * One console line, structured as far as the format allows.
 */
export type ParsedLine = { 
/**
 * Monotonic per-instance sequence number, assigned by the ring buffer.
 */
seq: number, 
/**
 * Wall-clock time this line was captured (RFC3339 UTC), not the server's stamp.
 */
capturedAt: string, 
/**
 * The server's own timestamp text (`12:34:56`), when it printed one.
 */
timestamp: string | null, level: LogLevel, thread: string | null, 
/**
 * The message with prefixes stripped, or the whole line when unparsed.
 */
message: string, 
/**
 * The original line, always kept verbatim for copy and search.
 */
raw: string, 
/**
 * True when the line came from stderr.
 */
stderr: boolean, };
