// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of the plan the user confirms.
 */
export type PlannedMod = { projectId: string, projectTitle: string, versionId: string, versionNumber: string, fileName: string, size: number | null, 
/**
 * 0 for what the user asked for, 1+ for what it pulled in.
 */
depth: number, 
/**
 * Which project required this one, when it was not asked for directly.
 */
requiredBy: string | null, 
/**
 * True when this exact file is already installed.
 */
alreadyInstalled: boolean, };
