// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerEvent = { uuid: string, 
/**
 * "join" or "leave".
 */
event: string, player: string, playerUuid: string | null, };
