// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BannedIp } from "./BannedIp";
import type { BannedPlayer } from "./BannedPlayer";
import type { OpEntry } from "./OpEntry";
import type { SeenPlayer } from "./SeenPlayer";
import type { WhitelistEntry } from "./WhitelistEntry";

/**
 * Everything the players view shows, read from the server's own files.
 */
export type PlayerLists = { ops: Array<OpEntry>, whitelist: Array<WhitelistEntry>, bannedPlayers: Array<BannedPlayer>, bannedIps: Array<BannedIp>, 
/**
 * Players seen in the console, newest first.
 */
seen: Array<SeenPlayer>, 
/**
 * Whether the whitelist is enforced at all (`white-list` in properties).
 */
whitelistEnabled: boolean, 
/**
 * Live instances take stdin commands; stopped ones are edited on disk.
 */
running: boolean, };
