// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";

/**
 * A project as a search result or a detail view.
 */
export type Project = { source: SourceId, 
/**
 * The source's own id, opaque to everything above this boundary.
 */
id: string, slug: string, title: string, description: string, author: string | null, downloads: number | null, iconUrl: string | null, pageUrl: string | null, categories: Array<string>, 
/**
 * Loader identifiers the project publishes for.
 */
loaders: Array<string>, };
