// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";
import type { SourceId } from "./SourceId";

/**
 * A project as a search result or a detail view.
 */
export type Project = { source: SourceId, 
/**
 * The source's own id, opaque to everything above this boundary.
 */
id: string, slug: string, title: string, description: string, author: string | null, downloads: number | null, iconUrl: string | null, pageUrl: string | null, categories: Array<string>, 
/**
 * Loader identifiers the project publishes for.
 */
loaders: Array<string>, 
/**
 * When the project last published something, as the source reports it.
 */
updated: string | null, 
/**
 * What kind of content this is, when the source says.
 */
contentType: ContentType | null, 
/**
 * False when the source will not serve the files through its API.
 *
 * CurseForge lets an author forbid third-party downloads, and a browser
 * that only fails at install time teaches nobody anything — so the card
 * says so and links to the page instead.
 */
downloadable: boolean, };
