// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyInfo } from "./KeyInfo";
import type { PropertyEntry } from "./PropertyEntry";

export type PropertiesView = { path: string, exists: boolean, 
/**
 * In file order, with unknown keys included.
 */
entries: Array<PropertyEntry>, 
/**
 * Known keys the file does not contain yet, offered as additions.
 */
missing: Array<KeyInfo>, 
/**
 * True when a restart is needed for edits to take effect.
 */
running: boolean, backupExists: boolean, };
