// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The public address, and what to hand somebody.
 */
export type PublicAddress = { address: string, 
/**
 * `address` or `address:port` — assembled here, like every other address
 * on this screen, rather than by the page.
 */
joinable: string, 
/**
 * True when the router's own external address is itself behind another
 * one, which is the case where port forwarding cannot work at all.
 */
carrierNat: boolean, };
