// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuitRequestedEvent = { 
/**
 * Names of instances that are still alive, for the confirmation dialog.
 */
liveInstances: Array<string>, };
