// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the outside world can get in — including not knowing.
 */
export type Reachability = { 
/**
 * `None` means the check could not be completed, which is not the same as
 * a closed port and is never rendered as one.
 */
reachable: boolean | null, 
/**
 * What was found, or why nothing could be.
 */
detail: string, 
/**
 * The address the outside service was asked about.
 */
askedAbout: string, };
