// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this machine can run a Minecraft server yet.
 *
 * The first-run screen asks this before offering anything: telling somebody to
 * create a server and only mentioning at launch that there is no Java is the
 * kind of thing that makes an app feel broken.
 */
export type Readiness = { 
/**
 * True while detection has never been run on this machine.
 */
javaScanPending: boolean, javaCount: number, 
/**
 * Highest usable major version found.
 */
newestJava: number | null, 
/**
 * Java needed by the newest Minecraft this app would install today.
 */
recommendedJava: number, 
/**
 * Set when nothing installed can run a current server.
 */
warning: string | null, instanceCount: number, };
