// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file that would go into the zip.
 */
export type ReportPart = { 
/**
 * Name inside the zip.
 */
name: string, 
/**
 * One line saying why it is useful, shown next to the preview.
 */
purpose: string, 
/**
 * The exact text that will be written.
 */
content: string, };
