// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportPart } from "./ReportPart";

/**
 * Everything the report will contain, before it is written anywhere.
 */
export type ReportPreview = { parts: Array<ReportPart>, 
/**
 * Suggested file name for the zip.
 */
suggestedName: string, totalBytes: number, 
/**
 * What a reader of the bundle can learn about this machine. Shown as a
 * warning, because folder names carry the user's account name.
 */
notice: string, };
