// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sample, as the charts read it.
 */
export type Sample = { ts: string, cpuPct: number, rssBytes: number, players: number | null, };
