// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveReport = { changed: Array<string>, 
/**
 * Set when the server is running, because the file is re-read only on boot.
 */
restartRequired: boolean, backupCreated: boolean, };
