// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When detection last ran, without asking about a particular instance.
 *
 * App settings show the detected list before any instance exists, so the age
 * of that list cannot be read out of one instance's status.
 */
export type ScanInfo = { lastScanAt: string | null, scanIsStale: boolean, };
