// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";
import type { Scope } from "./Scope";

/**
 * The fields the UI sends when creating or editing a schedule.
 */
export type ScheduleInput = { id: number | null, cron: string | null, intervalMinutes: number | null, scope: Scope, format: Format, compressionLevel: number | null, keepCount: number | null, keepDays: number | null, enabled: boolean, restartAfter: boolean, skipIfIdle: boolean, };
