// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";
import type { Scope } from "./Scope";

export type Schedule = { id: number, instanceId: number, 
/**
 * Daily time as `HH:MM`, when this is a daily schedule.
 */
cron: string | null, 
/**
 * Minutes between runs, when this is an interval schedule.
 */
intervalMinutes: number | null, scope: Scope, format: Format, compressionLevel: number | null, keepCount: number | null, keepDays: number | null, enabled: boolean, 
/**
 * Restart the server once the backup is done.
 */
restartAfter: boolean, 
/**
 * Skip the run when nobody has been online since the last one.
 */
skipIfIdle: boolean, lastRunAt: string | null, nextRunAt: string | null, };
