// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

/**
 * One page of results, with enough to drive pagination.
 */
export type SearchPage = { projects: Array<Project>, 
/**
 * Total matches the source reports, when it reports one.
 */
total: number | null, offset: number, limit: number, };
