// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to search for.
 */
export type SearchQuery = { text: string, 
/**
 * Loader identifiers to accept; empty means any.
 */
loaders: Array<string>, 
/**
 * Game versions to accept; empty means any.
 */
gameVersions: Array<string>, limit: number | null, offset: number | null, };
