// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";
import type { SortBy } from "./SortBy";

/**
 * What to search for.
 */
export type SearchQuery = { text: string, 
/**
 * Loader identifiers to accept; empty means any.
 */
loaders: Array<string>, 
/**
 * Game versions to accept; empty means any.
 */
gameVersions: Array<string>, limit: number | null, offset: number | null, sort: SortBy, 
/**
 * Category ids from the source's own list; empty means any.
 */
categories: Array<string>, contentType: ContentType, };
