// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How sure this app is that a pack will run as a server.
 */
export type ServerSupport = "yes" | "no" | "unknown";
