// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side a pack file is for.
 */
export type Side = "required" | "optional" | "unsupported";
