// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the results are ordered. Mapped onto each source's own parameter.
 */
export type SortBy = "relevance" | "popularity" | "downloads" | "recently_updated" | "newest";
