// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One downloadable file of a version.
 */
export type SourceFile = { url: string, fileName: string, sha1: string | null, sha512: string | null, size: number | null, 
/**
 * The file to install when a version ships several.
 */
primary: boolean, };
