// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";

/**
 * What a source can do right now, for the picker.
 */
export type SourceStatus = { id: SourceId, name: string, 
/**
 * False when the source needs something before it can be used.
 */
configured: boolean, 
/**
 * What is missing, and what to do about it.
 */
needs: string | null, 
/**
 * Where to get what it needs.
 */
setupUrl: string | null, };
