// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dependency } from "./Dependency";
import type { SourceFile } from "./SourceFile";
import type { SourceId } from "./SourceId";

/**
 * One release of a project.
 */
export type SourceVersion = { source: SourceId, id: string, projectId: string, name: string, 
/**
 * The version string the author chose, e.g. "0.5.11+mc1.21.4".
 */
versionNumber: string, 
/**
 * release | beta | alpha
 */
channel: string, published: string | null, gameVersions: Array<string>, loaders: Array<string>, files: Array<SourceFile>, dependencies: Array<Dependency>, };
