// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which source a project came from. Stored in `mods.source`.
 */
export type SourceId = "modrinth" | "curse_forge" | "local";
