// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Estimate } from "./Estimate";

/**
 * What a backup would cost, checked before it starts.
 */
export type SpaceCheck = { estimate: Estimate, requiredBytes: number, freeBytes: number | null, sufficient: boolean, 
/**
 * Set when there is not enough room, naming the shortfall.
 */
message: string | null, };
