// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far the stop sequence had to go. The UI shows this so "stopped" and
 * "had to be killed" are not the same word.
 */
export type StopStage = "already_stopped" | "graceful" | "terminated" | "killed";
