// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskProgressEvent = { taskId: string, 
/**
 * What kind of work this is: "install" for now.
 */
kind: string, 
/**
 * Which step: resolve, download, install, finalize.
 */
phase: string, done: number, total: number | null, message: string, instanceId: number | null, };
