// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskDoneEvent = { taskId: string, kind: string, ok: boolean, cancelled: boolean, 
/**
 * Rendered error message when `ok` is false.
 */
error: string | null, 
/**
 * Structured detail for errors that carry one (installer logs).
 */
errorKind: string | null, logPath: string | null, logTail: string | null, instanceId: number | null, };
