// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every field is optional: only what the UI sends is written.
 */
export type UpdateInstanceInput = { name: string | null, mcVersion: string | null, loaderVersion: string | null, javaPath: string | null | null, jvmArgs: Array<string> | null, serverArgs: Array<string> | null, minRamMb: number | null, maxRamMb: number | null, autoStart: boolean | null, autoRestart: boolean | null, restartMax: number | null, restartWindowS: number | null, stopTimeoutS: number | null, notes: string | null | null, color: string | null | null, };
