// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValueKind = { "kind": "bool" } | { "kind": "int", min: number | null, max: number | null, } | { "kind": "enum", options: Array<string>, } | { "kind": "text" };
