// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionKind } from "./VersionKind";

/**
 * One selectable Minecraft version.
 *
 * The date and the kind come from Mojang's manifest rather than from the id,
 * and they are what make a list of two hundred versions usable: "the one from
 * last March" is a question a table with dates can answer, and a dropdown
 * cannot.
 */
export type VersionEntry = { id: string, stable: boolean, 
/**
 * RFC3339, when the manifest lists this version. A build a provider
 * invented (a Paper release candidate) has none.
 */
releaseTime: string | null, kind: VersionKind, };
