// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of release a version is, as the picker's filters see it.
 *
 * Mojang's manifest has one `type` field, and it calls everything that is not
 * a release a `snapshot` - including the pre-releases and release candidates
 * that lead up to one. Those are the versions people deliberately go looking
 * for ("the 1.21.4 pre-release we were testing on"), so they are separated
 * out here by the only marker that exists: the id's own suffix.
 */
export type VersionKind = "release" | "snapshot" | "pre_release" | "ancient";
