// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chart window, which decides both the range and which resolution tier the
 * rows come from.
 */
export type Window = "hour" | "day" | "week" | "month";
