// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type World = { 
/**
 * Folder name, which is what `level-name` refers to.
 */
folder: string, path: string, 
/**
 * `LevelName` from level.dat, which the player chose and can differ.
 */
displayName: string | null, seed: number | null, gameType: string | null, hardcore: boolean, 
/**
 * Milliseconds since the epoch, as level.dat stores it.
 */
lastPlayed: number | null, 
/**
 * Minecraft version that last wrote the world.
 */
version: string | null, 
/**
 * True for the world the server will load.
 */
active: boolean, 
/**
 * Set when level.dat could not be read; the world is still listed.
 */
problem: string | null, 
/**
 * Where players appear, from `SpawnX`/`SpawnY`/`SpawnZ`. A map centred on
 * 0,0 is centred on nothing in particular; this is where the world is.
 */
spawnX: number | null, spawnY: number | null, spawnZ: number | null, };
